platform :ios, '8.0'
inhibit_all_warnings!
use_frameworks!

target 'SwiftVideoPlayerDemo' do

    pod 'SwiftVideoPlayer', :git => 'https://github.com/benjaminhorner/SwiftVideoPlayer.git'

end

target 'SwiftVideoPlayerDemoTests' do

end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['DYLIB_COMPATIBILITY_VERSION'] = ''
        end
    end
end
